<a href="https://colab.research.google.com/github/JillanCalvelo/LinearAlgebPublic/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab Activity 4:
##Matrices

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##Activity

###Task 1
Create a function named `desc_mat()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

### Function area

In [21]:
def desc_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

###Matrix Declaration

In [4]:

## Null Matrix
null_mat = np.array([])


In [8]:
## Zero Matrix
zero_mat_sqr = np.zeros((3,3))

In [7]:
## Ones Matrix
ones_mat_sqr = np.ones((3,3))

In [9]:
## Diagonal Matrix
A = np.array([
    [3, 0, 0],
    [0, 3, 0],
    [0, 0, 9]
])

In [13]:
## Identity Matrix
# np.identity(3)


In [17]:
## Upper Triangular Matrix
B = np.array([
    [1, 8, 1],
    [0, 4, 7],
    [0, 0, 9]
])

In [18]:
#Lower Triangular Matrix
C = np.array([
    [2, 0, 0],
    [6, 4, 0],
    [7, 7, 1]
])

### Test Areas

In [6]:
## Null Matrix
desc_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



In [10]:
## Zero Matrix
desc_mat(zero_mat_sqr)


Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2



In [11]:
## Ones Matrix
desc_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(3, 3)
Rank:	2



In [15]:
## Diagonal Matrix
desc_mat(A)

Matrix:
[[3 0 0]
 [0 3 0]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



In [14]:
## Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
## Upper Triangular Matrix
desc_mat(B)

Matrix:
[[1 8 1]
 [0 4 7]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



In [20]:
#Lower Triangular Matrix
desc_mat(C)

Matrix:
[[2 0 0]
 [6 4 0]
 [7 7 1]]

Shape:	(3, 3)
Rank:	2



###Task 2
Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

###Function area

In [22]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

###Matrix Declaration

In [23]:
## Addition
A = np.array([
    [3,1,9],
    [2,0,7],
    [7,1,7]
])
B = np.array([
    [3,2,3],
    [0,4,0],
    [1,1,1]
])

In [24]:
## Subtraction
D = np.array([
    [4,1,1],
    [3,5,5],
    [0,7,0]
])
E = np.array([
    [9,2,6],
    [9,1,0],
    [0,0,6]
])

In [32]:
## element-wise multiplication
F = np.array([
    [2,2,2],
    [4,3,4],
    [5,7,7]
])
G = np.array([
    [3,3,3],
    [0,1,9],
    [0,0,6]
])

In [42]:
## element-wise division
H = np.array([
    [10,12,21],
    [15,9,0],
    [20,22,11]
])
I = np.array([
    [2,6,7],
    [5,3,1],
    [10,11,1]
])

### Test Areas

In [25]:
## Addition
C = A+B
mat_operations(C)

Matrix:
[[ 6  3 12]
 [ 2  4  7]
 [ 8  2  8]]

Shape:	(3, 3)
Rank:	2



In [26]:
np.add(A,B)

array([[ 6,  3, 12],
       [ 2,  4,  7],
       [ 8,  2,  8]])

In [27]:
## Subtraction
S = D-E
mat_operations(S)

Matrix:
[[-5 -1 -5]
 [-6  4  5]
 [ 0  7 -6]]

Shape:	(3, 3)
Rank:	2



In [30]:
np.subtract(D,E)

array([[-5, -1, -5],
       [-6,  4,  5],
       [ 0,  7, -6]])

In [33]:
## element-wise multiplication
M = F*G
mat_operations(M)

Matrix:
[[ 6  6  6]
 [ 0  3 36]
 [ 0  0 42]]

Shape:	(3, 3)
Rank:	2



In [34]:
np.multiply(F,G)

array([[ 6,  6,  6],
       [ 0,  3, 36],
       [ 0,  0, 42]])

In [37]:
2*F

array([[ 4,  4,  4],
       [ 8,  6,  8],
       [10, 14, 14]])

In [39]:
4*G

array([[12, 12, 12],
       [ 0,  4, 36],
       [ 0,  0, 24]])

In [43]:
## element-wise division
V = H/I
mat_operations(V)

Matrix:
[[ 5.  2.  3.]
 [ 3.  3.  0.]
 [ 2.  2. 11.]]

Shape:	(3, 3)
Rank:	2



In [44]:
np.divide(H,I)

array([[ 5.,  2.,  3.],
       [ 3.,  3.,  0.],
       [ 2.,  2., 11.]])

In [47]:
H/5

array([[2. , 2.4, 4.2],
       [3. , 1.8, 0. ],
       [4. , 4.4, 2.2]])

In [48]:
1/I

array([[0.5       , 0.16666667, 0.14285714],
       [0.2       , 0.33333333, 1.        ],
       [0.1       , 0.09090909, 1.        ]])

## Conclusion

I therefore conclude that there is a variety of use of matrices and its different categories and elements at python and programming that we can manipulate and use in order to get different type of elemental values and linear combinations that then we can use to compute different matrix algebraic solutions such as addition and even element wise multiplication. .There are many ways that matrix operations do that would help in our technology and advancement today. One of the uses fpr matrices are to model the wireless signals and to optimize them. For detection, extractions and processing of the information embedded in signals matrices are used. Matrices play a key role in signal estimation and detection problems. They are used in sensor array signal processing and design of adaptive filters. Matrices help in processing and representing digital images.

##Reference:
 [1] N.A. “Application of Matrices”,taken from: https://www.vedantu.com/maths/application-of-matrices